language: ruby
rvm:
  - 2.6.0
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./.publish --only-4xx --check-favicon --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
